// VIDEOReducer
export const GET_VIDEO_BY_ID = 'VIDEO/GET_VIDEO_BY_ID'
export const GET_PLAYLIST_BY_ID = 'VIDEO/GET_PLAYLIST_BY_ID'

export const DISCOVER = 'VIDEO/DISCOVER'
export const TRENDING = 'VIDEO/TRENDING'
export const PLAYLIST = 'VIDEO/PLAYLIST'
export const TUTORIAL = 'VIDEO/TUTORIAL'
export const COMPETITION = 'VIDEO/COMPETITION'
export const REVIEW = 'VIDEO/REVIEW'
export const SKATING = 'VIDEO/SKATING'
export const OTHER = 'VIDEO/OTHER'


// AuthorizationReducer
export const AUTHORIZATION = 'AUTH/AUTHORIZATION'
export const REGISTRATION = 'AUTH/REGISTRATION'
export const LOGOUT = 'AUTH/LOGOUT'

// CHANNEL
export const AUTHOR_INFO = 'CHANNEL/AUTHOR_INFO'
export const CHANNEL_ABOUT = 'CHANNEL/AUTHOR_ABOUT'
export const CHANNEL_VIDEOS = 'CHANNEL/AUTHOR_VIDEOS'
export const CHANNEL_PLAYLIST = 'CHANNEL/AUTHOR_PLAYLIST'
export const CHANNEL_LIKES = 'CHANNEL/AUTHOR_PLAYLISTS'
export const CHANNEL_SUBSCRIPTIONS = 'CHANNEL/AUTHOR_SUBSCRIPTIONS'

// APPReducer
export const SUBSCRIPTIONS = 'APP/SUBSCRIPTIONS'
export const PROFILE = 'APP/PROFILE'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_MODAL = 'APP/SHOW_MODAL'
export const HIDE_MODAL = 'APP/HIDE_MODAL'

export const RERENDER = 'APP/RERENDER'
