export const GET_VIDEO_BY_ID = 'VIDEO/GET_VIDEO_BY_ID'

// AuthorizationReducer
export const AUTHORIZATION = 'AUTH/AUTHORIZATION'
export const REGISTRATION = 'AUTH/REGISTRATION'
export const LOGOUT = 'AUTH/LOGOUT'

export const AUTHOR_INFO = 'CHANNEL/AUTHOR_INFO'
export const CHANNEL_ABOUT = 'CHANNEL/AUTHOR_ABOUT'
export const CHANNEL_VIDEOS = 'CHANNEL/AUTHOR_VIDEOS'
export const CHANNEL_PLAYLIST = 'CHANNEL/AUTHOR_PLAYLIST'
export const CHANNEL_LIKES = 'CHANNEL/AUTHOR_PLAYLISTS'
export const CHANNEL_SUBSCRIPTIONS = 'CHANNEL/AUTHOR_SUBSCRIPTIONS'
// APPReducer

export const PROFILE = 'APP/PROFILE'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

